/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Apple Color Tokens
        'apple-white': '#ffffff',
        'apple-fog': '#f3f6f6',
        'apple-paper': '#fafafc',
        'apple-silver': '#e8e8ed',
        'apple-ash': '#dedfe2',
        'apple-graphite': '#6e6e73',
        'apple-charcoal': '#444545',
        'apple-steel': '#313131',
        'apple-ink': '#1d1d1f',
        'apple-black': '#000000',
        'apple-blue': '#0071e3',
        'apple-link': '#0066cc',
        'apple-ember': '#b64400',
        // Semantic aliases
        canvas: 'var(--color-canvas, #ffffff)',
        surface: 'var(--color-surface, #f3f6f6)',
        ink: 'var(--color-ink, #1d1d1f)',
        'ink-muted': 'var(--color-ink-muted, #6e6e73)',
        accent: 'var(--color-accent, #0071e3)',
        'accent-hover': 'var(--color-accent-hover, #005bb5)',
        border: 'var(--color-border, #dedfe2)',
      },
      fontFamily: {
        display: ['SF Pro Display', 'Inter', 'system-ui', 'sans-serif'],
        text: ['SF Pro Text', 'Inter', 'system-ui', 'sans-serif'],
        sans: ['SF Pro Text', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'caption': ['12px', { lineHeight: '1.33', letterSpacing: '-0.12px' }],
        'body-sm': ['14px', { lineHeight: '1.43', letterSpacing: '-0.22px' }],
        'body': ['17px', { lineHeight: '1.47', letterSpacing: '-0.37px' }],
        'subheading': ['21px', { lineHeight: '1.38', letterSpacing: '0.23px' }],
        'heading-sm': ['28px', { lineHeight: '1.14', letterSpacing: '0.2px' }],
        'heading': ['40px', { lineHeight: '1.1', letterSpacing: '-0.12px' }],
        'heading-lg': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px' }],
        'display': ['80px', { lineHeight: '1.05', letterSpacing: '-1.2px' }],
      },
      fontWeight: {
        regular: '400',
        semibold: '600',
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '9': '9px',
        '10': '10px',
        '11': '11px',
        '13': '13px',
        '14': '14px',
        '19': '19px',
        '20': '20px',
        '25': '25px',
        '28': '28px',
        '30': '30px',
        '40': '40px',
        '44': '44px',
        '57': '57px',
        '83': '83px',
      },
      borderRadius: {
        'card': '28px',
        'chip': '9999px',
        'button': '980px',
        'nav-pill': '32px',
        'small': '12px',
      },
      boxShadow: {
        'subtle': 'rgba(0, 0, 0, 0.11) 0px 0px 1px 0px inset',
        'xl': 'rgba(0, 0, 0, 0.05) 0px 0px 35px 20px',
      },
      maxWidth: {
        'page': '1440px',
      },
    },
  },
  plugins: [],
}